{% set name = "SZ3" %}
{% set version = "v3.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/szcompressor/{{ name }}
  git_tag: {{ version }}

build:
  skip: True  # [win or osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - gsl
    - zlib
    - zstd
  run:
    - gsl
    - zlib
    - zstd

about:
  home: https://github.com/szcompressor/SZ3
  license: BSD-3-Clause
  license_family: BSD
  license_file: copyright-and-BSD-license.txt
  summary: 'SZ3: A Modular Error-bounded Lossy Compression Framework for Scientific Datasets'
  description: |
    SZ3 - A Modular Error-bounded Lossy Compression Framework for Scientific Datasets
  doc_url: https://github.com/szcompressor/SZ
  dev_url: https://github.com/szcompressor/SZ

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

